Step 1) Import Required Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Step 2) Load Dataset

In [4]:
df=pd.read_csv('cardio.csv')

Step 3) Separate Input & Target

In [5]:
X = df.drop('cardio', axis=1)
y = df['cardio']

In [6]:
X.values

array([[0.0000e+00, 5.0000e+01, 1.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [1.0000e+00, 5.5000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.0000e+00, 5.2000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [6.9995e+04, 5.3000e+01, 1.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        1.0000e+00],
       [6.9998e+04, 6.1000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [6.9999e+04, 5.6000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00]])

X.values= This is done for faster Calculaitons   and it is called NumpyArray
np.random.seed(42) This is done to ensure same data split is done everytime
np.random.permutation this len(X_np) it shows th no of rows and we have to shuffle it and make it more random
split_index this is doen for trianing data to be 80 percent of data first are taken for training


Step 4) Manual Train–Test Split (NO LIBRARY)

In [7]:
X_np = X.values
Y_np = y.values
np.random.seed(42)
indices = np.random.permutation(len (X_np))
split_index = int(0.8 * len(X_np))
train_idx =  indices[:split_index]
test_idx = indices[split_index:]
X_train = X_np[train_idx]
X_test = X_np[test_idx]
y_train = Y_np[train_idx]
y_test = Y_np[test_idx]


Step 5) Initialize Parameters

Epochs =1000 this shows that our model will learn 1000 times it will iterate and learn. 

In [8]:
weights = np.zeros(X_train.shape[1])
bias =0
learning_rate = 0.01
epochs = 1000

Step 6) Sigmoid Function

any number it will convert it to Probability between zero and one 

In [9]:
def sigmoid(z):
    return 1 / (1+ np.exp(-z))

Step 7 Gradient Descent For Logistic Regression

In [10]:
# Step 7: Training using Gradient Descent
for i in range(epochs):
    # 1. Calculate linear combination
    z = np.dot(X_train, weights) + bias
    
    # 2. Apply stable sigmoid
    y_predicted = sigmoid(z)
    
    # 3. Calculate gradients
    dw = (1 / X_train.shape[0]) * np.dot(X_train.T, (y_predicted - y_train))
    db = (1 / X_train.shape[0]) * np.sum(y_predicted - y_train)
    
    # 4. Update weights and bias
    weights = weights - learning_rate * dw
    bias = bias - learning_rate * db

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11140\3813440747.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1+ np.exp(-z))


In [11]:
def sigmoid(z):
    # Stable sigmoid to avoid overflow
    return np.where(z >= 0, 1 / (1 + np.exp(-z)), np.exp(z) / (1 + np.exp(z)))


In [12]:
# Min-Max scaling (scale values between 0 and 1)
X_train = (X_train - X_train.min(axis=0)) / (X_train.max(axis=0) - X_train.min(axis=0))
X_test = (X_test - X_test.min(axis=0)) / (X_test.max(axis=0) - X_test.min(axis=0))


Step 8: Make Predictions on Test Data

In [13]:
# 1. Calculate linear combination for test data
z_test = np.dot(X_test, weights) + bias

# 2. Apply sigmoid to get probabilities
y_test_predicted = sigmoid(z_test)

# 3. Convert probabilities to class labels (0 or 1)
y_test_predicted_class = [1 if i > 0.5 else 0 for i in y_test_predicted]


Step 9: Check Model Accuracy

In [14]:
# Accuracy
accuracy = np.mean(y_test_predicted_class == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.5012399008079353


Step 10 : Confusion Matrix (Optional)

In [15]:
# Confusion Matrix
def confusion_matrix(y_true, y_pred):
    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))
    return np.array([[tp, fp],
                     [fn, tn]])

cm = confusion_matrix(y_test, y_test_predicted_class)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[0 0]
 [0 0]]


In [17]:
print(y_test_predicted[:10])


[1.         1.         1.         1.         1.         1.
 0.99999977 1.         1.         1.        ]


In [18]:
y_test_predicted_class = np.array([1 if i > 0.5 else 0 for i in y_test_predicted]).astype(int)

In [19]:
print(y_test_predicted_class[:10])

[1 1 1 1 1 1 1 1 1 1]


In [20]:
y_test_np = y_test.to_numpy().astype(int)
print(y_test_np[:10])


AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [21]:
# If y_test is already a NumPy array
y_test_np = y_test.astype(int)
print(y_test_np[:10])


[0 0 1 1 0 1 0 1 0 1]


In [22]:
def confusion_matrix(y_true, y_pred):
    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))
    return np.array([[tp, fp],
                     [fn, tn]])

cm = confusion_matrix(y_test_np, y_test_predicted_class)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[6266 6235]
 [   0    0]]


Accuracy Increase karva mate pela hati 50 Percentage Accuracy

STEP 1: FEATURE SCALING (MOST IMPORTANT)

In [23]:
# Feature Scaling (Standardization)
X_mean = X_train.mean(axis=0)
X_std = X_train.std(axis=0)

X_train = (X_train - X_mean) / X_std
X_test = (X_test - X_mean) / X_std


STEP 2: STABLE SIGMOID (NO OVERFLOW)

In [24]:
def sigmoid(z):
    return np.where(z >= 0,
                    1 / (1 + np.exp(-z)),
                    np.exp(z) / (1 + np.exp(z)))

STEP 3: RE-INITIALIZE PARAMETERS (RESET)

In [25]:
weights = np.zeros(X_train.shape[1])
bias = 0
learning_rate = 0.01
epochs = 3000

STEP 4: TRAIN AGAIN (GRADIENT DESCENT)

In [26]:
for i in range(epochs):
    z = np.dot(X_train, weights) + bias
    y_predicted = sigmoid(z)

    dw = (1 / X_train.shape[0]) * np.dot(X_train.T, (y_predicted - y_train))
    db = (1 / X_train.shape[0]) * np.sum(y_predicted - y_train)

    weights -= learning_rate * dw
    bias -= learning_rate * db

STEP 5: PREDICTION

In [27]:
z_test = np.dot(X_test, weights) + bias
y_test_pred = sigmoid(z_test)
y_test_pred_class = (y_test_pred >= 0.5).astype(int)

STEP 6: ACCURACY

In [30]:
accuracy = np.mean(y_test_pred_class == y_test)
print("Accuracy:", accuracy)    

Accuracy: 0.7192224622030238


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib
import os

# 1. Create the model directory if it doesn't exist
if not os.path.exists('model'):
    os.makedirs('model')

# 2. Load your dataset
print("Loading dataset...")
# Make sure this matches your file name exactly
df = pd.read_csv('ds_cvd_w1.csv') 

# 3. Clean and Train
# Drop ID if present
if 'id' in df.columns:
    df = df.drop(columns=['id'])

# Convert age from days to years if needed
if df['age'].mean() > 150:
    print("Converting age to years...")
    df['age'] = (df['age'] / 365.25).round().astype(int)

X = df.drop(columns=['cardio'])
y = df['cardio']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Model...")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 4. Save the model for the App
print("Saving model file...")
joblib.dump(model, 'model/cardio_model.pkl')
print("SUCCESS: model/cardio_model.pkl created!")

Loading dataset...
Converting age to years...
Training Model...
Saving model file...
SUCCESS: model/cardio_model.pkl created!
